config/routes.rb
Rails.application.routes.draw do
  mount Base => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

  devise_for :admins

  resources :instances

  root "home#index"
end

app/models/instance.rb
class Instance < ApplicationRecord
  has_many :users
  
  validates :company, presence: :true
  validates :server_url, presence: :true
  
  before_create :init_secret_key
  
  def base_url
    self.server_url + "/center/v1"
  end

  def query_user_url(id)
    base_url + "/rosters/" + id
  end

  def query_user(id)
    response = RestClient.get self.query_user_url(id)
    if response.code == 200
      return JSON.parse(response.body)
    end
    false
  rescue
    false
  end

  def query_thread_url(id)
    base_url + "/threads/" + id
  end

  def query_thread(id)
    response = RestClient.get self.query_thread_url(id)
    if response.code == 200
      return JSON.parse(response.body)
    end
  rescue
    false
  end

  def add_thread_member_url(id)
    base_url + "/threads/" + id + "/members"
  end

  def send_join_thread(thread_id, wechat_user)
    params = {
      wechat: {
        name: wechat_user.name,
        openId: wechat_user.openid
      }
    }
    response = RestClient.post self.add_thread_member_url(thread_id), params
    if response.code == 200
      return true
    end
  rescue
    false
  end

  def messages_url
    base_url + "/messages"
  end

  def send_message(message)
    thread = message.thread
    wechat_user = message.user
    params = {
      type: thread.category,
      id: thread.instance_thread_id,
      message: {
        content: message.content
      },
      wechat: {
        name:   wechat_user.name,
        openId: wechat_user.openid,
        avatar: wechat_user.icon
      }
    }

    response = RestClient.post self.messages_url, params
    logger.debug response
  rescue => e
    logger.debug e
  end

  private
  def init_secret_key
    self.app_key = SecureRandom.hex 8
    self.app_secret = Digest::SHA1.hexdigest("#{Time.now.to_i}")
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController

  def index
    @instances = Instance.page params[:page]
  end

  def new
    @instance = Instance.new
  end

  def create
    @instance = Instance.new instances_params
    if @instance.save
      redirect_to instances_path
    else
      render 'new'
    end
  end

  def edit
    @instance = Instance.find params[:id]
  end

  def update
    @instance = Instance.find params[:id]
    if @instance.update_attributes instances_params
      redirect_to instances_path
    else
      render 'edit'
    end
  end

  def destroy
    @instance = Instance.find params[:id]
    if @instance.destroy
      redirect_to instances_path
    end
  end

  private
  def instances_params
    params.require(:instance).permit(:server_url, :company)
  end

end

app/views/instances/_form.html.erb
<% if @instance.errors.any? %>
  <div class="alert alert-error">
    <ul style="margin:0 0 0px 25px">
      <% @instance.errors.messages.each do |key, msg| %>
        <li><%= key %> <%= msg.join(' ') %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@instance) do |f| %>
  <div class="form-group">
    <%= label_tag(:name, "企业名称") %>
    <%= f.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag(:server_url, "服务器地址") %>
    <%= f.text_field :server_url, class: "form-control", id: "server_url",  placeholder: "" %>
  </div>

  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/instances/edit.html.erb
<%= content_for :content_header do %>
  修改实例
<% end %>

<%= render partial: 'instances/form' %>

app/views/instances/index.html.erb
<%= content_for :content_header do %>
  实例列表
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>地址</th>
      <th>企业名称</th>
      <th>Key</th>
      <th>Secret</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @instances.each do |instance| %>
      <tr>
        <td><%= instance.server_url %></td>
        <td><%= instance.company %></td>
        <td><%= instance.app_key %></td>
        <td><%= instance.app_secret %></td>
        <td class="small text-muted">
          <%= link_to '编辑', edit_instance_path(instance) %>
          <%= link_to '删除', instance_path(instance), method: "delete", data: { confirm: '确认删除吗?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @instances %>

<%= link_to '创建实例',[:new, :instance],  class: 'btn btn-primary' %>

app/views/instances/new.html.erb
<%= content_for :content_header do %>
  创建实例
<% end %>

<%= render partial: 'instances/form' %>